spring.application.name=cinema

spring.datasource.url=jdbc:postgresql://localhost:5432/CinemaDB
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true